### ISSUE TITLE
Exec(...) Permission denied

### ISSUE THREAD

**Issue by AtomProgramer** [termux/termux-exec#10]
Hey, 
I installed node-red on my phone. I can run it with the command `node-red`. Now I want to start it by a widget or after booting. I created a file which says `node-red` in the .shortcuts directory but after I tabed on the widget this error message popped up
 `exec("/data/data/com.termux/files/home/.shortcuts/node-red"): Permission denied
[Process completed (code 1) - press Enter]`
The programming mosquitto worked with this method, whiteout problems.
Where is the problem and how can I solve it? Or is there another way to run node red after booting?
Sorry for my bad English, I am a student from Germany...

**Comment by Grimler91** [comment]
Hi, you need to give the file execution permission, run `chmod u+x $HOME/.shortcuts/node-red`.

It as good idea to add a proper shebang to the file as well, put `#!/data/data/com.termux/files/usr/bin/sh` as the first line.

**Comment by AtomProgramer** [comment]
When I run the first command I get the error message
`chmod: changing permissions of /data/data/com.termux/files/home/.shortcuts/node-red : operation not permitted`
I also tried to run it with tsu, but there I resived
`chmod cannot access /.shortcuts/node-red : No such file or directory`
I do not know if it's important, but I running it on cyanogenmod 13.

**Comment by Grimler91** [comment]
Have you symlinked the file to internal storage? 
What's the output of `realpath /data/data/com.termux/files/home/.shortcuts/node-red`?

**Comment by AtomProgramer** [comment]
I don't know. I simply installed it with this command's:

```
apt update
apt upgrade
apt install coreutils nano nodejs
npm i -g --unsafe-perm node-red
node-red
```

From [https://nodered.org/docs/platforms/android](url).

Wehn I try the realpath command the output is: `/data/data/com.termux/files/home/.shortcuts/node-red`

**Comment by Grimler91** [comment]
> I created a file which says node-red in the .shortcuts directory

does .shortcuts/node-red contain the text "node-red"? Or what's the content of it?

**Comment by AtomProgramer** [comment]
At the moment it contains
 ```
#!/data/data/com.termux/files/usr/bin/sh
node-red
```
 but if it is possible I want to add `termux-wake-lock`.

**Comment by Grimler91** [comment]
What's the output of `ls -al ~/.shortcuts/` and `stat -c "%a %n" ~.shortcuts`?

**Comment by AtomProgramer** [comment]
First:
```
drwx------  2 u0_a68 u0_a68 4096 Mar 31 22:55 .
drwx------ 11 u0_a68 u0_a68 4096 Mar 31 22:44 ..
-rwxrwxrwx  1 root   root     18 Mar 31 23:25 ND
---x------  1 root   root     49 Apr  1 18:40 node-red
```
Second:
`stat: cannot stat '~.shortcuts': No such file or directory`

**Comment by Grimler91** [comment]
Sorry, I meant `stat -c "%a %n" ~/.shortcuts`.

But anyways, the node-red file is owned by root, using root is generally a bad idea if you aren't 100 % sure what you're doing.

You need to change the owner back to the original user and then chmod it. 
```
tsu # or however you usually gain root access
chown u0_a68:u0_a68 ~/.shortcuts/node-red
```

Then, as the normal user
```
chmod u+x ~/.shortcuts/node-red
```

**Comment by AtomProgramer** [comment]
I dont get errors from the command's but when  I try to run the widget I receive:
`/data/data/com.termux/files/home/.shortcuts/node-red: 2: /data/data/com.termux/files/home/.shortcuts/node-red: node-red: not found`

**Comment by AtomProgramer** [comment]
From stat `-c "%a %n" ~/.shortcuts` I receive `700 /data/data/com.termux/files/home/.shortcuts`

**Comment by Grimler91** [comment]
So it can't find the program `node-red` then. Where is it? 
What's the output of `which node-red` and `ls -l $(realpath $(which node-red))`?

**Comment by AtomProgramer** [comment]
`/data/data/com.termux/files/user/bin/node-red`

**Comment by AtomProgramer** [comment]
I also replaced `node-red` with this path but it didn't worked either...

**Comment by Grimler91** [comment]
`/data/data/com.termux/files/user/bin/node-red` is a symlink to `/data/data/com.termux/files/user/bin/node-red`.

What's the output of `ls -l $(realpath $(which node-red))`?

**Comment by AtomProgramer** [comment]
`-rwx------ 1 u0_a68 u0_a68 11227 Mar 31 16:52 /data/data/com.termux/files/usr/lib/node_modules/node-red/red.js`

**Comment by Grimler91** [comment]
Alright, I tried it on my device. The node-red file uses this shebang: `#!/usr/bin/env node`. When executing it in a normal shell termux-exec saves the day by changing it to `#!/data/data/com.termux/files/usr/bin/env node`, this isn't done in the widget shell however.

Easiest fix for you would be to change your shortcut to something like this:
```
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
node $PREFIX/bin/node-red
```

We then ignore the shebang and tell it to parse the file with node.

**Comment by AtomProgramer** [comment]
OMG! It works!
Thank you so much!

**Comment by Grimler91** [comment]
@AtomProgramer no problem. Please close this issue if it is solved.

**Comment by AtomProgramer** [comment]
Close#10

**Comment by we-us** [comment]
chmod: cannot access 'kali-armhf/usr/bin/sudo': No such file or directory
Please help

**Comment by Ahmet311y** [comment]
İ have a problem chmod: cannot access 'webpwn3r.py': No such file or directory
