### ISSUE TITLE
kubectl calls not rewritten

### ISSUE THREAD

**Issue by gsf** [termux/termux-exec#13]
Not sure if there's a fix here but thought this was worth noting. In trying to get gcloud and kubectl working in termux, I found that gcloud works fine but not when called by kubectl:

```
$ which gcloud
/data/data/com.termux/files/usr/google-cloud-sdk/bin/gcloud
$ head -n1 /data/data/com.termux/files/usr/google-cloud-sdk/bin/gcloud
#!/bin/sh
$ gcloud config config-helper --format=json
{
  "configuration": {
    "active_configuration": "default",
...
$ kubectl get pod
Unable to connect to the server: error executing access token command "/data/data/com.termux/files/usr/google-cloud
-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /data/data/com.termux/files/usr/google-cloud-sdk
/bin/gcloud: no such file or directory output= stderr=
```

If the hashbang in the gcloud script is changed to `/data/data/com.termux/files/usr/bin/sh` then the kubectl command works.

Note that this is the binary for kubectl at https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl (amd64 since I'm on a Chromebook). I haven't tried compiling it locally yet.

**Comment by fornwall** [comment]
Sorry for the really late response here. This is probably due to the binary not going through libc for execve(), and instead using the syscall directly, which this tool does not rewrite.

**Comment by fornwall** [comment]
Does the `kubectl` Termux package work any better?

**Comment by gsf** [comment]
I'm afraid I'm not working with any gcloud infrastructure at the moment so can't test.

**Comment by ghost** [comment]
Closing as this should be fixed with `kubectl` Termux package. Sideloaded binaries obtained from Github may not work, especially if they are not dynamically linked with libc.
