### ISSUE TITLE
termux-exec not found

### ISSUE THREAD

**Issue by ronnac** [termux/termux-exec#16]
$ pkg install termux-exec
Reading package lists... Done                  Building dependency tree
Reading state information... Done              termux-exec is already the newest version (0.4-1).                                            0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                               
$ termux-exec
No command termux-exec found, did you mean:     Command termux-open in package termux-tools   
$ termux-info
Packages CPU architecture:
arm                                            Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/pointless.list                deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-16046393 #1 SMP PREEMPT Wed Oct 9 14:44:51 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105FN

**Comment by Grimler91** [comment]
It's not a command, it's a library. 

```
$ dpkg -L termux-exec
/.
/data
/data/data
/data/data/com.termux
/data/data/com.termux/files
/data/data/com.termux/files/usr
/data/data/com.termux/files/usr/lib
/data/data/com.termux/files/usr/lib/libtermux-exec.so
/data/data/com.termux/files/usr/share
/data/data/com.termux/files/usr/share/doc
/data/data/com.termux/files/usr/share/doc/termux-exec
/data/data/com.termux/files/usr/share/doc/termux-exec/LICENSE
```
