### ISSUE TITLE
Visibility of files created/managed by Termux to other applications such like Kodi

### ISSUE THREAD

**Issue by xeviff** [termux/termux-exec#20]
Hi!
I'm installing rclone on my Nvidia Shield TV with this Magisk Module: 
https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone

Finally I could execute it (despite it's a 32bits arch) and I thought that I won when I saw the GDrive directories doing an "ls" command
![image](https://user-images.githubusercontent.com/73612508/118262824-bc875c80-b4b5-11eb-8b65-9565ef8e3185.png)

But later, in Kodi I discovered that it has no visibility of anyone:
![image](https://user-images.githubusercontent.com/73612508/118262993-f8222680-b4b5-11eb-80f9-0acd008dfb35.png)

I tried a "chmod", and I was thinking with a "chown", because it seems like a permissions issue (as root is the owner of this folders as image shows:)
![image](https://user-images.githubusercontent.com/73612508/118263291-59e29080-b4b6-11eb-89d8-bc39c0cb7bb0.png)
(by the way, interesting these "total 0" isn't it?)

But if I want to know the user that executes kodi, with an "ps aux | grep kodi" nothing is showed (and it seems here is not showing all the process of the Android System).
![image](https://user-images.githubusercontent.com/73612508/118263437-91513d00-b4b6-11eb-86b3-ec32dd43f6ab.png)

I'm a little lost at this point, so I was wondering If I could get some recomendation from your expertise.
Thanks a lot for advance and have a nice day!

**Comment by sylirre** [comment]
This issue is irrelevant to `termux-exec`, so I'm closing it.

***

As for the described problem itself, the app can't see files because of a different mount namespace. You need to run utility under master mount namespace (`su` option `--mount-master`, applicable to Magisk).
