### ISSUE TITLE
termux-exec vs fixedshell

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-exec#3]
This Project seems to be very similar to https://github.com/its-pointless/fixedshell/. Both are probably based of rkeene's initial programm. But fixedshell is a little more advanced by now. At least it doesn't suffer from #2. Maybe the code of libandroid-fixshebang.c could replace the one from termux-exec.c? 

I do like that termux-exec is always active, as opposed to fixedshell's activation script.

**Comment by fornwall** [comment]
#2 should be fixed now, thanks!

Yes, rkeene got this started, huge thanks to him! Hopefully we can have this included by default and come pre-installed - in the meantime, please test out and report any issues!

I'll look over https://github.com/its-pointless/fixedshell/ and see how things can be merged - I'll bring it up on irc&gitter.

**Comment by its-pointless** [comment]
My code is in general fairly terrible. From that probably best to let fornwall do this.
