### ISSUE TITLE
termux-exec breaks proot

### ISSUE THREAD

**Issue by Maxxie** [termux/termux-exec#8]
Proot usage is broken by the termux-exec injection mechanism.
This is reproducible by simply trying to use proot, as it complains that it cannot find "/bin/sh".
Also launching proot to some other shell not in /bin seems to work (still all /bin commands won't work).
There should be an environment variable or some other way to disable termux-exec when not needed.

**Comment by Grimler91** [comment]
termux-exec sets `LD_PRELOAD`, so `unset LD_PRELOAD` should disable it. 

We could perhaps document this better. 

edit: sorry, LD_PRELOAD, not LD_LIBRARY_PATH

**Comment by Maxxie** [comment]
Thank you, I had naively tried export LD_PRELOAD="" and it wouldn't work, sorry for wasting your time.
