### ISSUE TITLE
CANNOT LINK EXECUTABLE when using su.

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-exec#9]
```
$ su -c input keyevent 26
CANNOT LINK EXECUTABLE "/system/bin/dex2oat": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
```
Maybe LD_PRELOAD needs to be cleared by `su`? 

Altough I am not sure clearing that variable is the best solution, as it is also used by various other programs. Most notably torsocks,  tsocks and proxychains. Maybe we need to remove termux-exec from the variable while leaving other paths behind.

**Comment by Boss9599** [comment]
I  have same problem with termux
